2019-09-23 18:07:06 main ERROR root:66 - Wrong initialize connection pool
by.epam.crackertracker.exception.TrackerConnectionPoolException: Wrong create connection
	at by.epam.crackertracker.creator.ConnectionCreatorTrackerJdbc.newConnection(ConnectionCreatorTrackerJdbc.java:32)
	at by.epam.crackertracker.pool.ConnectionPool.init(ConnectionPool.java:62)
	at by.epam.crackertracker.pool.ConnectionPool.<init>(ConnectionPool.java:49)
	at by.epam.crackertracker.pool.ConnectionPool.getInstance(ConnectionPool.java:90)
	at by.epam.crackertracker.dao.AdviceDaoJdbcImpl.insert(AdviceDaoJdbcImpl.java:35)
	at by.epam.crackertracker.dao.AdviceDaoJdbcTest.testInsert(AdviceDaoJdbcTest.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:138)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:393)
	at org.postgresql.Driver.connect(Driver.java:267)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at by.epam.crackertracker.creator.ConnectionCreatorTrackerJdbc.newConnection(ConnectionCreatorTrackerJdbc.java:28)
	... 29 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at org.postgresql.core.PGStream.<init>(PGStream.java:62)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:76)
	... 40 more
2019-09-23 18:07:06 main FATAL root:51 - by.epam.crackertracker.exception.TrackerConnectionPoolException: Wrong initialize connection pool
2019-09-23 18:07:52 main ERROR root:31 - Wrong create connection
org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:138)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:393)
	at org.postgresql.Driver.connect(Driver.java:267)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at by.epam.crackertracker.creator.ConnectionCreatorTrackerJdbc.newConnection(ConnectionCreatorTrackerJdbc.java:28)
	at by.epam.crackertracker.pool.ConnectionPool.init(ConnectionPool.java:62)
	at by.epam.crackertracker.pool.ConnectionPool.<init>(ConnectionPool.java:49)
	at by.epam.crackertracker.pool.ConnectionPool.getInstance(ConnectionPool.java:90)
	at by.epam.crackertracker.dao.AdviceDaoJdbcImpl.insert(AdviceDaoJdbcImpl.java:35)
	at by.epam.crackertracker.dao.AdviceDaoJdbcTest.testInsert(AdviceDaoJdbcTest.java:45)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at org.postgresql.core.PGStream.<init>(PGStream.java:62)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:76)
	... 40 more
2019-09-23 18:07:52 main ERROR root:66 - Wrong initialize connection pool
by.epam.crackertracker.exception.TrackerConnectionPoolException: Wrong create connection
	at by.epam.crackertracker.creator.ConnectionCreatorTrackerJdbc.newConnection(ConnectionCreatorTrackerJdbc.java:32)
	at by.epam.crackertracker.pool.ConnectionPool.init(ConnectionPool.java:62)
	at by.epam.crackertracker.pool.ConnectionPool.<init>(ConnectionPool.java:49)
	at by.epam.crackertracker.pool.ConnectionPool.getInstance(ConnectionPool.java:90)
	at by.epam.crackertracker.dao.AdviceDaoJdbcImpl.insert(AdviceDaoJdbcImpl.java:35)
	at by.epam.crackertracker.dao.AdviceDaoJdbcTest.testInsert(AdviceDaoJdbcTest.java:45)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:138)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:393)
	at org.postgresql.Driver.connect(Driver.java:267)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at by.epam.crackertracker.creator.ConnectionCreatorTrackerJdbc.newConnection(ConnectionCreatorTrackerJdbc.java:28)
	... 29 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at org.postgresql.core.PGStream.<init>(PGStream.java:62)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:76)
	... 40 more
2019-09-23 18:07:52 main FATAL root:51 - by.epam.crackertracker.exception.TrackerConnectionPoolException: Wrong initialize connection pool
2019-09-23 18:08:14 main ERROR root:31 - Wrong create connection
org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:138)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:393)
	at org.postgresql.Driver.connect(Driver.java:267)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at by.epam.crackertracker.creator.ConnectionCreatorTrackerJdbc.newConnection(ConnectionCreatorTrackerJdbc.java:28)
	at by.epam.crackertracker.pool.ConnectionPool.init(ConnectionPool.java:62)
	at by.epam.crackertracker.pool.ConnectionPool.<init>(ConnectionPool.java:49)
	at by.epam.crackertracker.pool.ConnectionPool.getInstance(ConnectionPool.java:90)
	at by.epam.crackertracker.dao.AdviceDaoJdbcImpl.insert(AdviceDaoJdbcImpl.java:35)
	at by.epam.crackertracker.dao.AdviceDaoJdbcTest.testInsert(AdviceDaoJdbcTest.java:45)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at org.postgresql.core.PGStream.<init>(PGStream.java:62)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:76)
	... 40 more
2019-09-23 18:08:14 main ERROR root:66 - Wrong initialize connection pool
by.epam.crackertracker.exception.TrackerConnectionPoolException: Wrong create connection
	at by.epam.crackertracker.creator.ConnectionCreatorTrackerJdbc.newConnection(ConnectionCreatorTrackerJdbc.java:32)
	at by.epam.crackertracker.pool.ConnectionPool.init(ConnectionPool.java:62)
	at by.epam.crackertracker.pool.ConnectionPool.<init>(ConnectionPool.java:49)
	at by.epam.crackertracker.pool.ConnectionPool.getInstance(ConnectionPool.java:90)
	at by.epam.crackertracker.dao.AdviceDaoJdbcImpl.insert(AdviceDaoJdbcImpl.java:35)
	at by.epam.crackertracker.dao.AdviceDaoJdbcTest.testInsert(AdviceDaoJdbcTest.java:45)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:138)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:393)
	at org.postgresql.Driver.connect(Driver.java:267)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at by.epam.crackertracker.creator.ConnectionCreatorTrackerJdbc.newConnection(ConnectionCreatorTrackerJdbc.java:28)
	... 29 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at org.postgresql.core.PGStream.<init>(PGStream.java:62)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:76)
	... 40 more
2019-09-23 18:08:14 main FATAL root:51 - by.epam.crackertracker.exception.TrackerConnectionPoolException: Wrong initialize connection pool
2019-09-23 18:09:35 main ERROR root:31 - Wrong create connection
org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:138)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:393)
	at org.postgresql.Driver.connect(Driver.java:267)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at by.epam.crackertracker.creator.ConnectionCreatorTrackerJdbc.newConnection(ConnectionCreatorTrackerJdbc.java:28)
	at by.epam.crackertracker.pool.ConnectionPool.init(ConnectionPool.java:62)
	at by.epam.crackertracker.pool.ConnectionPool.<init>(ConnectionPool.java:49)
	at by.epam.crackertracker.pool.ConnectionPool.getInstance(ConnectionPool.java:90)
	at by.epam.crackertracker.dao.AdviceDaoJdbcImpl.insert(AdviceDaoJdbcImpl.java:35)
	at by.epam.crackertracker.dao.AdviceDaoJdbcTest.testInsert(AdviceDaoJdbcTest.java:45)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at org.postgresql.core.PGStream.<init>(PGStream.java:62)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:76)
	... 40 more
2019-09-23 18:09:35 main ERROR root:66 - Wrong initialize connection pool
by.epam.crackertracker.exception.TrackerConnectionPoolException: Wrong create connection
	at by.epam.crackertracker.creator.ConnectionCreatorTrackerJdbc.newConnection(ConnectionCreatorTrackerJdbc.java:32)
	at by.epam.crackertracker.pool.ConnectionPool.init(ConnectionPool.java:62)
	at by.epam.crackertracker.pool.ConnectionPool.<init>(ConnectionPool.java:49)
	at by.epam.crackertracker.pool.ConnectionPool.getInstance(ConnectionPool.java:90)
	at by.epam.crackertracker.dao.AdviceDaoJdbcImpl.insert(AdviceDaoJdbcImpl.java:35)
	at by.epam.crackertracker.dao.AdviceDaoJdbcTest.testInsert(AdviceDaoJdbcTest.java:45)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:138)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:393)
	at org.postgresql.Driver.connect(Driver.java:267)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at by.epam.crackertracker.creator.ConnectionCreatorTrackerJdbc.newConnection(ConnectionCreatorTrackerJdbc.java:28)
	... 29 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at org.postgresql.core.PGStream.<init>(PGStream.java:62)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:76)
	... 40 more
2019-09-23 18:09:35 main FATAL root:51 - by.epam.crackertracker.exception.TrackerConnectionPoolException: Wrong initialize connection pool
2019-09-24 10:44:24 main INFO  root:29 - connection created
2019-09-24 10:44:24 main INFO  root:29 - connection created
2019-09-24 10:44:24 main INFO  root:29 - connection created
2019-09-24 10:44:24 main INFO  root:29 - connection created
2019-09-24 10:44:24 main INFO  root:29 - connection created
2019-09-24 10:44:24 main INFO  root:29 - connection created
2019-09-24 10:44:24 main INFO  root:29 - connection created
2019-09-24 10:44:24 main INFO  root:29 - connection created
2019-09-24 10:44:24 main INFO  root:29 - connection created
2019-09-24 10:44:24 main INFO  root:29 - connection created
2019-09-24 10:44:24 main INFO  root:70 - Connection pool with 10 connections was created
2019-09-24 10:44:24 main DEBUG root:92 - Connaction Pool was created
2019-09-24 10:44:24 main ERROR root:46 - org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "advices_pkey"
  Detail: Key (idadvices)=(1) already exists.
2019-09-24 10:45:04 main INFO  root:29 - connection created
2019-09-24 10:45:04 main INFO  root:29 - connection created
2019-09-24 10:45:04 main INFO  root:29 - connection created
2019-09-24 10:45:04 main INFO  root:29 - connection created
2019-09-24 10:45:04 main INFO  root:29 - connection created
2019-09-24 10:45:04 main INFO  root:29 - connection created
2019-09-24 10:45:04 main INFO  root:29 - connection created
2019-09-24 10:45:04 main INFO  root:29 - connection created
2019-09-24 10:45:04 main INFO  root:29 - connection created
2019-09-24 10:45:04 main INFO  root:29 - connection created
2019-09-24 10:45:04 main INFO  root:70 - Connection pool with 10 connections was created
2019-09-24 10:45:04 main DEBUG root:92 - Connaction Pool was created
2019-09-24 10:45:04 main ERROR root:46 - org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "advices_pkey"
  Detail: Key (idadvices)=(1) already exists.
2019-09-24 10:45:54 main INFO  root:29 - connection created
2019-09-24 10:45:54 main INFO  root:29 - connection created
2019-09-24 10:45:54 main INFO  root:29 - connection created
2019-09-24 10:45:54 main INFO  root:29 - connection created
2019-09-24 10:45:54 main INFO  root:29 - connection created
2019-09-24 10:45:54 main INFO  root:29 - connection created
2019-09-24 10:45:54 main INFO  root:29 - connection created
2019-09-24 10:45:54 main INFO  root:29 - connection created
2019-09-24 10:45:54 main INFO  root:29 - connection created
2019-09-24 10:45:54 main INFO  root:29 - connection created
2019-09-24 10:45:54 main INFO  root:70 - Connection pool with 10 connections was created
2019-09-24 10:45:54 main DEBUG root:92 - Connaction Pool was created
2019-09-24 10:45:54 main DEBUG root:67 - 1 advice deleted
2019-09-24 10:46:18 main INFO  root:29 - connection created
2019-09-24 10:46:18 main INFO  root:29 - connection created
2019-09-24 10:46:18 main INFO  root:29 - connection created
2019-09-24 10:46:18 main INFO  root:29 - connection created
2019-09-24 10:46:18 main INFO  root:29 - connection created
2019-09-24 10:46:19 main INFO  root:29 - connection created
2019-09-24 10:46:19 main INFO  root:29 - connection created
2019-09-24 10:46:19 main INFO  root:29 - connection created
2019-09-24 10:46:19 main INFO  root:29 - connection created
2019-09-24 10:46:19 main INFO  root:29 - connection created
2019-09-24 10:46:19 main INFO  root:70 - Connection pool with 10 connections was created
2019-09-24 10:46:19 main DEBUG root:92 - Connaction Pool was created
2019-09-24 10:46:38 main INFO  root:29 - connection created
2019-09-24 10:46:38 main INFO  root:29 - connection created
2019-09-24 10:46:38 main INFO  root:29 - connection created
2019-09-24 10:46:38 main INFO  root:29 - connection created
2019-09-24 10:46:38 main INFO  root:29 - connection created
2019-09-24 10:46:38 main INFO  root:29 - connection created
2019-09-24 10:46:38 main INFO  root:29 - connection created
2019-09-24 10:46:38 main INFO  root:29 - connection created
2019-09-24 10:46:38 main INFO  root:29 - connection created
2019-09-24 10:46:38 main INFO  root:29 - connection created
2019-09-24 10:46:38 main INFO  root:70 - Connection pool with 10 connections was created
2019-09-24 10:46:38 main DEBUG root:92 - Connaction Pool was created
2019-09-24 10:47:32 main INFO  root:29 - connection created
2019-09-24 10:47:32 main INFO  root:29 - connection created
2019-09-24 10:47:32 main INFO  root:29 - connection created
2019-09-24 10:47:32 main INFO  root:29 - connection created
2019-09-24 10:47:32 main INFO  root:29 - connection created
2019-09-24 10:47:33 main INFO  root:29 - connection created
2019-09-24 10:47:33 main INFO  root:29 - connection created
2019-09-24 10:47:33 main INFO  root:29 - connection created
2019-09-24 10:47:33 main INFO  root:29 - connection created
2019-09-24 10:47:33 main INFO  root:29 - connection created
2019-09-24 10:47:33 main INFO  root:70 - Connection pool with 10 connections was created
2019-09-24 10:47:33 main DEBUG root:92 - Connaction Pool was created
2019-09-24 10:47:33 main DEBUG root:67 - 2 advice deleted
2019-09-24 10:47:50 main INFO  root:29 - connection created
2019-09-24 10:47:50 main INFO  root:29 - connection created
2019-09-24 10:47:50 main INFO  root:29 - connection created
2019-09-24 10:47:50 main INFO  root:29 - connection created
2019-09-24 10:47:51 main INFO  root:29 - connection created
2019-09-24 10:47:51 main INFO  root:29 - connection created
2019-09-24 10:47:51 main INFO  root:29 - connection created
2019-09-24 10:47:51 main INFO  root:29 - connection created
2019-09-24 10:47:51 main INFO  root:29 - connection created
2019-09-24 10:47:51 main INFO  root:29 - connection created
2019-09-24 10:47:51 main INFO  root:70 - Connection pool with 10 connections was created
2019-09-24 10:47:51 main DEBUG root:92 - Connaction Pool was created
2019-09-24 10:58:26 main INFO  root:29 - connection created
2019-09-24 10:58:26 main INFO  root:29 - connection created
2019-09-24 10:58:26 main INFO  root:29 - connection created
2019-09-24 10:58:26 main INFO  root:29 - connection created
2019-09-24 10:58:26 main INFO  root:29 - connection created
2019-09-24 10:58:27 main INFO  root:29 - connection created
2019-09-24 10:58:27 main INFO  root:29 - connection created
2019-09-24 10:58:27 main INFO  root:29 - connection created
2019-09-24 10:58:27 main INFO  root:29 - connection created
2019-09-24 10:58:27 main INFO  root:29 - connection created
2019-09-24 10:58:27 main INFO  root:70 - Connection pool with 10 connections was created
2019-09-24 10:58:27 main DEBUG root:92 - Connaction Pool was created
2019-09-24 10:58:27 main DEBUG root:67 - 2 advice deleted
2019-09-24 11:05:19 main INFO  root:29 - connection created
2019-09-24 11:05:19 main INFO  root:29 - connection created
2019-09-24 11:05:19 main INFO  root:29 - connection created
2019-09-24 11:05:19 main INFO  root:29 - connection created
2019-09-24 11:05:19 main INFO  root:29 - connection created
2019-09-24 11:05:19 main INFO  root:29 - connection created
2019-09-24 11:05:19 main INFO  root:29 - connection created
2019-09-24 11:05:19 main INFO  root:29 - connection created
2019-09-24 11:05:19 main INFO  root:29 - connection created
2019-09-24 11:05:20 main INFO  root:29 - connection created
2019-09-24 11:05:20 main INFO  root:70 - Connection pool with 10 connections was created
2019-09-24 11:05:20 main DEBUG root:92 - Connaction Pool was created
2019-09-24 11:05:20 main ERROR root:46 - org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "advices_pkey"
  Detail: Key (idadvices)=(1) already exists.
2019-09-24 11:12:18 main INFO  root:29 - connection created
2019-09-24 11:12:18 main INFO  root:29 - connection created
2019-09-24 11:12:18 main INFO  root:29 - connection created
2019-09-24 11:12:18 main INFO  root:29 - connection created
2019-09-24 11:12:18 main INFO  root:29 - connection created
2019-09-24 11:12:18 main INFO  root:29 - connection created
2019-09-24 11:12:18 main INFO  root:29 - connection created
2019-09-24 11:12:18 main INFO  root:29 - connection created
2019-09-24 11:12:18 main INFO  root:29 - connection created
2019-09-24 11:12:18 main INFO  root:29 - connection created
2019-09-24 11:12:18 main INFO  root:70 - Connection pool with 10 connections was created
2019-09-24 11:12:18 main DEBUG root:92 - Connaction Pool was created
2019-09-24 11:12:18 main DEBUG root:41 - test test 1234 - advice inserted
2019-09-24 11:12:18 main ERROR root:43 - asdsadsadasdsadsadsda
2019-09-24 12:03:15 main INFO  root:29 - connection created
2019-09-24 12:03:15 main INFO  root:29 - connection created
2019-09-24 12:03:15 main INFO  root:29 - connection created
2019-09-24 12:03:15 main INFO  root:29 - connection created
2019-09-24 12:03:15 main INFO  root:29 - connection created
2019-09-24 12:03:15 main INFO  root:29 - connection created
2019-09-24 12:03:15 main INFO  root:29 - connection created
2019-09-24 12:03:15 main INFO  root:29 - connection created
2019-09-24 12:03:15 main INFO  root:29 - connection created
2019-09-24 12:03:15 main INFO  root:29 - connection created
2019-09-24 12:03:15 main INFO  root:70 - Connection pool with 10 connections was created
2019-09-24 12:03:15 main DEBUG root:92 - Connaction Pool was created
2019-09-24 12:03:15 main ERROR root:46 - org.postgresql.util.PSQLException: ERROR: value too long for type character varying(100)
2019-09-24 12:03:15 main DEBUG root:41 - Р‘РЈР“РђР“Рђ - advice inserted
2019-09-24 12:03:15 main ERROR root:43 - asdsadsadasdsadsadsda
2019-09-24 12:03:15 main DEBUG root:67 - 3 advice deleted
2019-09-24 12:03:15 main DEBUG root:67 - 2 advice deleted
2019-09-24 12:03:49 main INFO  root:29 - connection created
2019-09-24 12:03:49 main INFO  root:29 - connection created
2019-09-24 12:03:49 main INFO  root:29 - connection created
2019-09-24 12:03:49 main INFO  root:29 - connection created
2019-09-24 12:03:49 main INFO  root:29 - connection created
2019-09-24 12:03:49 main INFO  root:29 - connection created
2019-09-24 12:03:49 main INFO  root:29 - connection created
2019-09-24 12:03:49 main INFO  root:29 - connection created
2019-09-24 12:03:49 main INFO  root:29 - connection created
2019-09-24 12:03:49 main INFO  root:29 - connection created
2019-09-24 12:03:49 main INFO  root:70 - Connection pool with 10 connections was created
2019-09-24 12:03:49 main DEBUG root:92 - Connaction Pool was created
2019-09-24 12:04:25 main INFO  root:29 - connection created
2019-09-24 12:04:25 main INFO  root:29 - connection created
2019-09-24 12:04:25 main INFO  root:29 - connection created
2019-09-24 12:04:25 main INFO  root:29 - connection created
2019-09-24 12:04:25 main INFO  root:29 - connection created
2019-09-24 12:04:25 main INFO  root:29 - connection created
2019-09-24 12:04:25 main INFO  root:29 - connection created
2019-09-24 12:04:25 main INFO  root:29 - connection created
2019-09-24 12:04:25 main INFO  root:29 - connection created
2019-09-24 12:04:25 main INFO  root:29 - connection created
2019-09-24 12:04:25 main INFO  root:70 - Connection pool with 10 connections was created
2019-09-24 12:04:25 main DEBUG root:92 - Connaction Pool was created
2019-09-24 12:05:15 main INFO  root:29 - connection created
2019-09-24 12:05:15 main INFO  root:29 - connection created
2019-09-24 12:05:15 main INFO  root:29 - connection created
2019-09-24 12:05:15 main INFO  root:29 - connection created
2019-09-24 12:05:15 main INFO  root:29 - connection created
2019-09-24 12:05:15 main INFO  root:29 - connection created
2019-09-24 12:05:15 main INFO  root:29 - connection created
2019-09-24 12:05:15 main INFO  root:29 - connection created
2019-09-24 12:05:15 main INFO  root:29 - connection created
2019-09-24 12:05:15 main INFO  root:29 - connection created
2019-09-24 12:05:15 main INFO  root:70 - Connection pool with 10 connections was created
2019-09-24 12:05:15 main DEBUG root:92 - Connaction Pool was created
2019-09-24 12:05:31 main INFO  root:29 - connection created
2019-09-24 12:05:31 main INFO  root:29 - connection created
2019-09-24 12:05:31 main INFO  root:29 - connection created
2019-09-24 12:05:31 main INFO  root:29 - connection created
2019-09-24 12:05:31 main INFO  root:29 - connection created
2019-09-24 12:05:31 main INFO  root:29 - connection created
2019-09-24 12:05:31 main INFO  root:29 - connection created
2019-09-24 12:05:32 main INFO  root:29 - connection created
2019-09-24 12:05:32 main INFO  root:29 - connection created
2019-09-24 12:05:32 main INFO  root:29 - connection created
2019-09-24 12:05:32 main INFO  root:70 - Connection pool with 10 connections was created
2019-09-24 12:05:32 main DEBUG root:92 - Connaction Pool was created
2019-09-24 12:06:08 main INFO  root:29 - connection created
2019-09-24 12:06:09 main INFO  root:29 - connection created
2019-09-24 12:06:09 main INFO  root:29 - connection created
2019-09-24 12:06:09 main INFO  root:29 - connection created
2019-09-24 12:06:09 main INFO  root:29 - connection created
2019-09-24 12:06:09 main INFO  root:29 - connection created
2019-09-24 12:06:09 main INFO  root:29 - connection created
2019-09-24 12:06:09 main INFO  root:29 - connection created
2019-09-24 12:06:09 main INFO  root:29 - connection created
2019-09-24 12:06:09 main INFO  root:29 - connection created
2019-09-24 12:06:09 main INFO  root:70 - Connection pool with 10 connections was created
2019-09-24 12:06:09 main DEBUG root:92 - Connaction Pool was created
2019-09-24 12:06:41 main INFO  root:29 - connection created
2019-09-24 12:06:41 main INFO  root:29 - connection created
2019-09-24 12:06:41 main INFO  root:29 - connection created
2019-09-24 12:06:41 main INFO  root:29 - connection created
2019-09-24 12:06:41 main INFO  root:29 - connection created
2019-09-24 12:06:42 main INFO  root:29 - connection created
2019-09-24 12:06:42 main INFO  root:29 - connection created
2019-09-24 12:06:42 main INFO  root:29 - connection created
2019-09-24 12:06:42 main INFO  root:29 - connection created
2019-09-24 12:06:42 main INFO  root:29 - connection created
2019-09-24 12:06:42 main INFO  root:70 - Connection pool with 10 connections was created
2019-09-24 12:06:42 main DEBUG root:92 - Connaction Pool was created
2019-09-24 12:07:10 main INFO  root:29 - connection created
2019-09-24 12:07:10 main INFO  root:29 - connection created
2019-09-24 12:07:10 main INFO  root:29 - connection created
2019-09-24 12:07:10 main INFO  root:29 - connection created
2019-09-24 12:07:11 main INFO  root:29 - connection created
2019-09-24 12:07:11 main INFO  root:29 - connection created
2019-09-24 12:07:11 main INFO  root:29 - connection created
2019-09-24 12:07:11 main INFO  root:29 - connection created
2019-09-24 12:07:11 main INFO  root:29 - connection created
2019-09-24 12:07:11 main INFO  root:29 - connection created
2019-09-24 12:07:11 main INFO  root:70 - Connection pool with 10 connections was created
2019-09-24 12:07:11 main DEBUG root:92 - Connaction Pool was created
2019-09-24 12:07:33 main INFO  root:29 - connection created
2019-09-24 12:07:33 main INFO  root:29 - connection created
2019-09-24 12:07:33 main INFO  root:29 - connection created
2019-09-24 12:07:33 main INFO  root:29 - connection created
2019-09-24 12:07:33 main INFO  root:29 - connection created
2019-09-24 12:07:33 main INFO  root:29 - connection created
2019-09-24 12:07:33 main INFO  root:29 - connection created
2019-09-24 12:07:33 main INFO  root:29 - connection created
2019-09-24 12:07:33 main INFO  root:29 - connection created
2019-09-24 12:07:33 main INFO  root:29 - connection created
2019-09-24 12:07:33 main INFO  root:70 - Connection pool with 10 connections was created
2019-09-24 12:07:33 main DEBUG root:92 - Connaction Pool was created
2019-09-24 12:07:33 main DEBUG root:67 - 2 advice deleted
2019-09-24 12:08:15 main INFO  root:29 - connection created
2019-09-24 12:08:15 main INFO  root:29 - connection created
2019-09-24 12:08:15 main INFO  root:29 - connection created
2019-09-24 12:08:15 main INFO  root:29 - connection created
2019-09-24 12:08:15 main INFO  root:29 - connection created
2019-09-24 12:08:15 main INFO  root:29 - connection created
2019-09-24 12:08:15 main INFO  root:29 - connection created
2019-09-24 12:08:16 main INFO  root:29 - connection created
2019-09-24 12:08:16 main INFO  root:29 - connection created
2019-09-24 12:08:16 main INFO  root:29 - connection created
2019-09-24 12:08:16 main INFO  root:70 - Connection pool with 10 connections was created
2019-09-24 12:08:16 main DEBUG root:92 - Connaction Pool was created
2019-09-24 12:08:16 main DEBUG root:67 - 2 advice deleted
2019-09-24 12:08:31 main INFO  root:29 - connection created
2019-09-24 12:08:31 main INFO  root:29 - connection created
2019-09-24 12:08:31 main INFO  root:29 - connection created
2019-09-24 12:08:31 main INFO  root:29 - connection created
2019-09-24 12:08:31 main INFO  root:29 - connection created
2019-09-24 12:08:31 main INFO  root:29 - connection created
2019-09-24 12:08:31 main INFO  root:29 - connection created
2019-09-24 12:08:31 main INFO  root:29 - connection created
2019-09-24 12:08:31 main INFO  root:29 - connection created
2019-09-24 12:08:31 main INFO  root:29 - connection created
2019-09-24 12:08:31 main INFO  root:70 - Connection pool with 10 connections was created
2019-09-24 12:08:31 main DEBUG root:92 - Connaction Pool was created
2019-09-24 12:08:55 main INFO  root:29 - connection created
2019-09-24 12:08:55 main INFO  root:29 - connection created
2019-09-24 12:08:55 main INFO  root:29 - connection created
2019-09-24 12:08:55 main INFO  root:29 - connection created
2019-09-24 12:08:55 main INFO  root:29 - connection created
2019-09-24 12:08:55 main INFO  root:29 - connection created
2019-09-24 12:08:55 main INFO  root:29 - connection created
2019-09-24 12:08:55 main INFO  root:29 - connection created
2019-09-24 12:08:55 main INFO  root:29 - connection created
2019-09-24 12:08:55 main INFO  root:29 - connection created
2019-09-24 12:08:55 main INFO  root:70 - Connection pool with 10 connections was created
2019-09-24 12:08:55 main DEBUG root:92 - Connaction Pool was created
2019-09-24 12:08:55 main ERROR root:46 - org.postgresql.util.PSQLException: ERROR: value too long for type character varying(100)
2019-09-24 12:09:31 main INFO  root:29 - connection created
2019-09-24 12:09:31 main INFO  root:29 - connection created
2019-09-24 12:09:31 main INFO  root:29 - connection created
2019-09-24 12:09:31 main INFO  root:29 - connection created
2019-09-24 12:09:31 main INFO  root:29 - connection created
2019-09-24 12:09:31 main INFO  root:29 - connection created
2019-09-24 12:09:31 main INFO  root:29 - connection created
2019-09-24 12:09:31 main INFO  root:29 - connection created
2019-09-24 12:09:31 main INFO  root:29 - connection created
2019-09-24 12:09:31 main INFO  root:29 - connection created
2019-09-24 12:09:31 main INFO  root:70 - Connection pool with 10 connections was created
2019-09-24 12:09:31 main DEBUG root:92 - Connaction Pool was created
2019-09-24 12:09:31 main DEBUG root:41 - Р‘РЈР“РђР“Рђ - advice inserted
2019-09-24 12:09:31 main ERROR root:43 - asdsadsadasdsadsadsda
2019-09-24 12:10:06 main INFO  root:29 - connection created
2019-09-24 12:10:07 main INFO  root:29 - connection created
2019-09-24 12:10:07 main INFO  root:29 - connection created
2019-09-24 12:10:07 main INFO  root:29 - connection created
2019-09-24 12:10:07 main INFO  root:29 - connection created
2019-09-24 12:10:07 main INFO  root:29 - connection created
2019-09-24 12:10:07 main INFO  root:29 - connection created
2019-09-24 12:10:07 main INFO  root:29 - connection created
2019-09-24 12:10:07 main INFO  root:29 - connection created
2019-09-24 12:10:07 main INFO  root:29 - connection created
2019-09-24 12:10:07 main INFO  root:70 - Connection pool with 10 connections was created
2019-09-24 12:10:07 main DEBUG root:92 - Connaction Pool was created
2019-09-24 12:10:07 main DEBUG root:41 - Р‘РЈР“РђР“Рђ - advice inserted
2019-09-24 12:10:07 main ERROR root:43 - asdsadsadasdsadsadsda
2019-09-24 12:10:39 main INFO  root:29 - connection created
2019-09-24 12:10:39 main INFO  root:29 - connection created
2019-09-24 12:10:39 main INFO  root:29 - connection created
2019-09-24 12:10:39 main INFO  root:29 - connection created
2019-09-24 12:10:39 main INFO  root:29 - connection created
2019-09-24 12:10:39 main INFO  root:29 - connection created
2019-09-24 12:10:39 main INFO  root:29 - connection created
2019-09-24 12:10:39 main INFO  root:29 - connection created
2019-09-24 12:10:39 main INFO  root:29 - connection created
2019-09-24 12:10:39 main INFO  root:29 - connection created
2019-09-24 12:10:39 main INFO  root:70 - Connection pool with 10 connections was created
2019-09-24 12:10:39 main DEBUG root:92 - Connaction Pool was created
2019-09-24 12:10:39 main DEBUG root:41 - Р‘РЈР“РђР“Рђ - advice inserted
2019-09-24 12:10:39 main ERROR root:43 - asdsadsadasdsadsadsda
2019-09-24 12:12:57 main INFO  root:29 - connection created
2019-09-24 12:12:57 main INFO  root:29 - connection created
2019-09-24 12:12:57 main INFO  root:29 - connection created
2019-09-24 12:12:57 main INFO  root:29 - connection created
2019-09-24 12:12:57 main INFO  root:29 - connection created
2019-09-24 12:12:57 main INFO  root:29 - connection created
2019-09-24 12:12:57 main INFO  root:29 - connection created
2019-09-24 12:12:57 main INFO  root:29 - connection created
2019-09-24 12:12:57 main INFO  root:29 - connection created
2019-09-24 12:12:57 main INFO  root:29 - connection created
2019-09-24 12:12:57 main INFO  root:70 - Connection pool with 10 connections was created
2019-09-24 12:12:57 main DEBUG root:92 - Connaction Pool was created
2019-09-24 12:13:23 main INFO  root:29 - connection created
2019-09-24 12:13:23 main INFO  root:29 - connection created
2019-09-24 12:13:23 main INFO  root:29 - connection created
2019-09-24 12:13:23 main INFO  root:29 - connection created
2019-09-24 12:13:23 main INFO  root:29 - connection created
2019-09-24 12:13:23 main INFO  root:29 - connection created
2019-09-24 12:13:23 main INFO  root:29 - connection created
2019-09-24 12:13:23 main INFO  root:29 - connection created
2019-09-24 12:13:23 main INFO  root:29 - connection created
2019-09-24 12:13:23 main INFO  root:29 - connection created
2019-09-24 12:13:23 main INFO  root:70 - Connection pool with 10 connections was created
2019-09-24 12:13:23 main DEBUG root:92 - Connaction Pool was created
2019-09-24 12:15:56 main INFO  root:29 - connection created
2019-09-24 12:15:56 main INFO  root:29 - connection created
2019-09-24 12:15:56 main INFO  root:29 - connection created
2019-09-24 12:15:57 main INFO  root:29 - connection created
2019-09-24 12:15:57 main INFO  root:29 - connection created
2019-09-24 12:15:57 main INFO  root:29 - connection created
2019-09-24 12:15:57 main INFO  root:29 - connection created
2019-09-24 12:15:57 main INFO  root:29 - connection created
2019-09-24 12:15:57 main INFO  root:29 - connection created
2019-09-24 12:15:57 main INFO  root:29 - connection created
2019-09-24 12:15:57 main INFO  root:70 - Connection pool with 10 connections was created
2019-09-24 12:15:57 main DEBUG root:92 - Connaction Pool was created
2019-09-24 12:15:57 main DEBUG root:41 - Р‘РЈР“РђР“Рђ - advice inserted
2019-09-24 12:15:57 main ERROR root:43 - asdsadsadasdsadsadsda
2019-09-24 12:16:18 main INFO  root:29 - connection created
2019-09-24 12:16:18 main INFO  root:29 - connection created
2019-09-24 12:16:18 main INFO  root:29 - connection created
2019-09-24 12:16:18 main INFO  root:29 - connection created
2019-09-24 12:16:18 main INFO  root:29 - connection created
2019-09-24 12:16:18 main INFO  root:29 - connection created
2019-09-24 12:16:18 main INFO  root:29 - connection created
2019-09-24 12:16:18 main INFO  root:29 - connection created
2019-09-24 12:16:18 main INFO  root:29 - connection created
2019-09-24 12:16:18 main INFO  root:29 - connection created
2019-09-24 12:16:18 main INFO  root:70 - Connection pool with 10 connections was created
2019-09-24 12:16:18 main DEBUG root:92 - Connaction Pool was created
2019-09-24 12:16:18 main DEBUG root:41 - Р‘РЈР“РђР“Рђ - advice inserted
2019-09-24 12:16:18 main ERROR root:43 - asdsadsadasdsadsadsda
2019-09-24 12:19:15 main INFO  root:29 - connection created
2019-09-24 12:19:15 main INFO  root:29 - connection created
2019-09-24 12:19:15 main INFO  root:29 - connection created
2019-09-24 12:19:15 main INFO  root:29 - connection created
2019-09-24 12:19:15 main INFO  root:29 - connection created
2019-09-24 12:19:15 main INFO  root:29 - connection created
2019-09-24 12:19:15 main INFO  root:29 - connection created
2019-09-24 12:19:15 main INFO  root:29 - connection created
2019-09-24 12:19:15 main INFO  root:29 - connection created
2019-09-24 12:19:15 main INFO  root:29 - connection created
2019-09-24 12:19:15 main INFO  root:70 - Connection pool with 10 connections was created
2019-09-24 12:19:15 main DEBUG root:92 - Connaction Pool was created
2019-09-24 12:21:14 main INFO  root:29 - connection created
2019-09-24 12:21:14 main INFO  root:29 - connection created
2019-09-24 12:21:14 main INFO  root:29 - connection created
2019-09-24 12:21:14 main INFO  root:29 - connection created
2019-09-24 12:21:14 main INFO  root:29 - connection created
2019-09-24 12:21:15 main INFO  root:29 - connection created
2019-09-24 12:21:15 main INFO  root:29 - connection created
2019-09-24 12:21:15 main INFO  root:29 - connection created
2019-09-24 12:21:15 main INFO  root:29 - connection created
2019-09-24 12:21:15 main INFO  root:29 - connection created
2019-09-24 12:21:15 main INFO  root:70 - Connection pool with 10 connections was created
2019-09-24 12:21:15 main DEBUG root:92 - Connaction Pool was created
2019-09-24 12:21:15 main ERROR root:46 - org.postgresql.util.PSQLException: ERROR: null value in column "message" violates not-null constraint
  Detail: Failing row contains (3, null).
2019-09-24 12:22:23 main INFO  root:29 - connection created
2019-09-24 12:22:23 main INFO  root:29 - connection created
2019-09-24 12:22:23 main INFO  root:29 - connection created
2019-09-24 12:22:23 main INFO  root:29 - connection created
2019-09-24 12:22:23 main INFO  root:29 - connection created
2019-09-24 12:22:23 main INFO  root:29 - connection created
2019-09-24 12:22:23 main INFO  root:29 - connection created
2019-09-24 12:22:23 main INFO  root:29 - connection created
2019-09-24 12:22:23 main INFO  root:29 - connection created
2019-09-24 12:22:23 main INFO  root:29 - connection created
2019-09-24 12:22:23 main INFO  root:70 - Connection pool with 10 connections was created
2019-09-24 12:22:23 main DEBUG root:92 - Connaction Pool was created
2019-09-24 12:24:47 main INFO  root:29 - connection created
2019-09-24 12:24:47 main INFO  root:29 - connection created
2019-09-24 12:24:47 main INFO  root:29 - connection created
2019-09-24 12:24:48 main INFO  root:29 - connection created
2019-09-24 12:24:48 main INFO  root:29 - connection created
2019-09-24 12:24:48 main INFO  root:29 - connection created
2019-09-24 12:24:48 main INFO  root:29 - connection created
2019-09-24 12:24:48 main INFO  root:29 - connection created
2019-09-24 12:24:48 main INFO  root:29 - connection created
2019-09-24 12:24:48 main INFO  root:29 - connection created
2019-09-24 12:24:48 main INFO  root:70 - Connection pool with 10 connections was created
2019-09-24 12:24:48 main DEBUG root:92 - Connaction Pool was created
2019-09-24 12:25:41 main INFO  root:29 - connection created
2019-09-24 12:25:41 main INFO  root:29 - connection created
2019-09-24 12:25:41 main INFO  root:29 - connection created
2019-09-24 12:25:41 main INFO  root:29 - connection created
2019-09-24 12:25:41 main INFO  root:29 - connection created
2019-09-24 12:25:41 main INFO  root:29 - connection created
2019-09-24 12:25:41 main INFO  root:29 - connection created
2019-09-24 12:25:41 main INFO  root:29 - connection created
2019-09-24 12:25:41 main INFO  root:29 - connection created
2019-09-24 12:25:41 main INFO  root:29 - connection created
2019-09-24 12:25:41 main INFO  root:70 - Connection pool with 10 connections was created
2019-09-24 12:25:41 main DEBUG root:92 - Connaction Pool was created
2019-09-24 13:32:30 main INFO  root:29 - connection created
2019-09-24 13:32:30 main INFO  root:29 - connection created
2019-09-24 13:32:30 main INFO  root:29 - connection created
2019-09-24 13:32:30 main INFO  root:29 - connection created
2019-09-24 13:32:30 main INFO  root:29 - connection created
2019-09-24 13:32:30 main INFO  root:29 - connection created
2019-09-24 13:32:30 main INFO  root:29 - connection created
2019-09-24 13:32:31 main INFO  root:29 - connection created
2019-09-24 13:32:31 main INFO  root:29 - connection created
2019-09-24 13:32:31 main INFO  root:29 - connection created
2019-09-24 13:32:31 main INFO  root:70 - Connection pool with 10 connections was created
2019-09-24 13:32:31 main DEBUG root:92 - Connaction Pool was created
2019-09-24 13:32:31 main ERROR root:55 - org.postgresql.util.PSQLException: ERROR: operator does not exist: boolean = integer
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 128
2019-09-24 13:34:05 main INFO  root:29 - connection created
2019-09-24 13:34:05 main INFO  root:29 - connection created
2019-09-24 13:34:05 main INFO  root:29 - connection created
2019-09-24 13:34:05 main INFO  root:29 - connection created
2019-09-24 13:34:05 main INFO  root:29 - connection created
2019-09-24 13:34:05 main INFO  root:29 - connection created
2019-09-24 13:34:05 main INFO  root:29 - connection created
2019-09-24 13:34:05 main INFO  root:29 - connection created
2019-09-24 13:34:05 main INFO  root:29 - connection created
2019-09-24 13:34:05 main INFO  root:29 - connection created
2019-09-24 13:34:05 main INFO  root:70 - Connection pool with 10 connections was created
2019-09-24 13:34:05 main DEBUG root:92 - Connaction Pool was created
2019-09-24 13:34:05 main ERROR root:55 - org.postgresql.util.PSQLException: ERROR: operator does not exist: boolean = integer
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 128
2019-09-24 13:35:01 main INFO  root:29 - connection created
2019-09-24 13:35:01 main INFO  root:29 - connection created
2019-09-24 13:35:01 main INFO  root:29 - connection created
2019-09-24 13:35:01 main INFO  root:29 - connection created
2019-09-24 13:35:01 main INFO  root:29 - connection created
2019-09-24 13:35:01 main INFO  root:29 - connection created
2019-09-24 13:35:01 main INFO  root:29 - connection created
2019-09-24 13:35:02 main INFO  root:29 - connection created
2019-09-24 13:35:02 main INFO  root:29 - connection created
2019-09-24 13:35:02 main INFO  root:29 - connection created
2019-09-24 13:35:02 main INFO  root:70 - Connection pool with 10 connections was created
2019-09-24 13:35:02 main DEBUG root:92 - Connaction Pool was created
2019-09-24 13:35:02 main ERROR root:55 - org.postgresql.util.PSQLException: ERROR: operator does not exist: boolean = integer
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 128
2019-09-24 13:35:25 main INFO  root:29 - connection created
2019-09-24 13:35:25 main INFO  root:29 - connection created
2019-09-24 13:35:25 main INFO  root:29 - connection created
2019-09-24 13:35:25 main INFO  root:29 - connection created
2019-09-24 13:35:25 main INFO  root:29 - connection created
2019-09-24 13:35:25 main INFO  root:29 - connection created
2019-09-24 13:35:25 main INFO  root:29 - connection created
